### ISSUE TITLE
Closing peer when receiving UPDATE messages

### ISSUE THREAD

**Issue by gregfoletta** [gregfoletta/bgp_listener#2]
=================================================================
==435707==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 2176 byte(s) in 4 object(s) allocated from:
    #0 0x7f11e5a02867 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x55d136902132 in parse_update /home/gjf/Documents/Projects/bgpsee/bgp_message.c:390
    #2 0x55d1368ff636 in recv_msg /home/gjf/Documents/Projects/bgpsee/bgp_message.c:124
    #3 0x55d1368fae0d in bgp_peer_thread /home/gjf/Documents/Projects/bgpsee/bgp.c:313
    #4 0x7f11e509eb42 in start_thread nptl/pthread_create.c:442

Direct leak of 176 byte(s) in 11 object(s) allocated from:
    #0 0x7f11e5a02867 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x55d13690172a in parse_update_attr /home/gjf/Documents/Projects/bgpsee/bgp_message.c:337
    #2 0x55d13690262f in parse_update /home/gjf/Documents/Projects/bgpsee/bgp_message.c:405
    #3 0x55d1368ff636 in recv_msg /home/gjf/Documents/Projects/bgpsee/bgp_message.c:124
    #4 0x55d1368fae0d in bgp_peer_thread /home/gjf/Documents/Projects/bgpsee/bgp.c:313
    #5 0x7f11e509eb42 in start_thread nptl/pthread_create.c:442

Direct leak of 128 byte(s) in 1 object(s) allocated from:
    #0 0x7f11e5a02867 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x55d1368fa690 in bgp_peer_thread /home/gjf/Documents/Projects/bgpsee/bgp.c:286
    #2 0x7f11e509eb42 in start_thread nptl/pthread_create.c:442

Direct leak of 72 byte(s) in 12 object(s) allocated from:
    #0 0x7f11e5a02867 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x55d136902dc5 in parse_update /home/gjf/Documents/Projects/bgpsee/bgp_message.c:423
    #2 0x55d1368ff636 in recv_msg /home/gjf/Documents/Projects/bgpsee/bgp_message.c:124
    #3 0x55d1368fae0d in bgp_peer_thread /home/gjf/Documents/Projects/bgpsee/bgp.c:313
    #4 0x7f11e509eb42 in start_thread nptl/pthread_create.c:442

Direct leak of 72 byte(s) in 1 object(s) allocated from:
    #0 0x7f11e5a02867 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x55d1368fee1e in recv_msg /home/gjf/Documents/Projects/bgpsee/bgp_message.c:82
    #2 0x55d1368fae0d in bgp_peer_thread /home/gjf/Documents/Projects/bgpsee/bgp.c:313
    #3 0x7f11e509eb42 in start_thread nptl/pthread_create.c:442

Indirect leak of 64 byte(s) in 4 object(s) allocated from:
    #0 0x7f11e5a02867 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x55d13690172a in parse_update_attr /home/gjf/Documents/Projects/bgpsee/bgp_message.c:337
    #2 0x55d13690262f in parse_update /home/gjf/Documents/Projects/bgpsee/bgp_message.c:405
    #3 0x55d1368ff636 in recv_msg /home/gjf/Documents/Projects/bgpsee/bgp_message.c:124
    #4 0x55d1368fae0d in bgp_peer_thread /home/gjf/Documents/Projects/bgpsee/bgp.c:313
    #5 0x7f11e509eb42 in start_thread nptl/pthread_create.c:442

**Comment by gregfoletta** [comment]
These memory leaks have now been resolved.
